### ISSUE TITLE
Trying to allocate negative number of bytes

### ISSUE THREAD

**Issue by dedmen** [gildor2/UModel#10]
```
appMalloc:size=-1 <- UnPackage::LoadNameTable <- UnPackage::UnPackage:Content/System/Engine.u, ver=129/27, game=2007 <- UnPackage::LoadPackage:Content/System/Engine.u <- CUmodelApp::ShowPackageUI <- Main:umodel_version=459
```

```
appMalloc:size=-1632 <- FArray::Empty:-24 x 68 <- TArray::Serialize:0/0 <- USkeletalMesh::Serialize <- LoadObject:SkeletalMesh'AbombStageLights.AbombStageLights', pos=2C41, ver=129/22, game=2000 <- UObject::EndLoad <- LoadWholePackage:AbombStageLights <- CUmodelApp::ShowPackageUI <- Main:umodel_version=459
```

When trying to unpack files from Swat 4.

**Comment by gildor2** [comment]
This is absolutely correct error message when
a) game is not supported
b) umodel wasn't set up for correct package reading.

In your case, this is b). If you'd take a look at the compatibility table, you'd notice a link to forum thread about this game: http://www.gildor.org/smf/index.php/topic,553.0.html - please read it carefully (especially MY messages).

**Comment by dedmen** [comment]
Oh im sorry. I tried it first with overriding game detection but then it crashed and then i used it without. Now it works.. Should i open another ticket when i find the old crash again or just post it here?

**Comment by gildor2** [comment]
Usually people providing feedback on gildor.org forums. "Issues" on GitHub are not so useful, and would be used more if forum won't exist.
