### ISSUE TITLE
Pressing export and files not appearing in export folder

### ISSUE THREAD

**Issue by savageduckerino** [gildor2/UModel#101]
> Loading package: /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_01.uasset Ver: 516/0 Engine: 0 [Unversioned] Names: 18 Exports: 1 Imports: 3 Game: 1000140
Loading package: /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_Cue.uasset Ver: 516/0 Engine: 0 [Unversioned] Names: 49 Exports: 5 Imports: 15 Game: 1000140
Memory: allocated 74643803 bytes in 284103 blocks
Loading SoundWave DudeBro_Amb_Music_01 from package /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_01.uasset
WARNING: IntProperty "USoundWave::NumChannels" was not found
WARNING: IntProperty "USoundWave::RawPCMDataSize" was not found
WARNING: IntProperty "USoundWave::SampleRate" was not found
WARNING: FloatProperty "USoundWave::Duration" was not found
******** Loading object SoundWave'DudeBro_Amb_Music_01.DudeBro_Amb_Music_01' ********
*** USoundWave: streaming data: 10 chunks in format OPUS
USoundWave DudeBro_Amb_Music_01: dropping 262464 bytes
Loaded in 0.004 sec, 5 allocs, 0.00 MBytes serialized in 1 calls.
Exporting objects ...
Exporting SoundWave DudeBro_Amb_Music_01 to D:/Users/krave/Videos/exports/Athena/Sounds/Events/CubeIsland
Memory: allocated 74660347 bytes in 284106 blocks
Loaded in 0 sec, 1 allocs, 0.00 MBytes serialized in 0 calls.
Exporting objects ...
Memory: allocated 74660347 bytes in 284106 blocks

I do this and the files I chose to export don't appear in my export folder

**Comment by savageduckerino** [comment]
> > Loading package: /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_01.uasset Ver: 516/0 Engine: 0 [Unversioned] Names: 18 Exports: 1 Imports: 3 Game: 1000140
> > Loading package: /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_Cue.uasset Ver: 516/0 Engine: 0 [Unversioned] Names: 49 Exports: 5 Imports: 15 Game: 1000140
> > Memory: allocated 74643803 bytes in 284103 blocks
> > Loading SoundWave DudeBro_Amb_Music_01 from package /FortniteGame/Content/Athena/Sounds/Events/CubeIsland/DudeBro_Amb_Music_01.uasset
> > WARNING: IntProperty "USoundWave::NumChannels" was not found
> > WARNING: IntProperty "USoundWave::RawPCMDataSize" was not found
> > WARNING: IntProperty "USoundWave::SampleRate" was not found
> > WARNING: FloatProperty "USoundWave::Duration" was not found
> > ******** Loading object SoundWave'DudeBro_Amb_Music_01.DudeBro_Amb_Music_01' ********
> > *** USoundWave: streaming data: 10 chunks in format OPUS
> > USoundWave DudeBro_Amb_Music_01: dropping 262464 bytes
> > Loaded in 0.004 sec, 5 allocs, 0.00 MBytes serialized in 1 calls.
> > Exporting objects ...
> > Exporting SoundWave DudeBro_Amb_Music_01 to D:/Users/krave/Videos/exports/Athena/Sounds/Events/CubeIsland
> > Memory: allocated 74660347 bytes in 284106 blocks
> > Loaded in 0 sec, 1 allocs, 0.00 MBytes serialized in 0 calls.
> > Exporting objects ...
> > Memory: allocated 74660347 bytes in 284106 blocks
> 
> I do this and the files I chose to export don't appear in my export folder

**Comment by gildor2** [comment]
This is OPUS sound, it won't work. Look over other issues for more info (there's already issue about it).
