### ISSUE TITLE
How do I export something raw without converting it?

### ISSUE THREAD

**Issue by Khodyn** [gildor2/UModel#102]
I want to export an OPUS sound file, but UModel is trying to convert it, fails, then doesn't give me any file.
Since UModel can't convert it, I want to do it myself but there's no way to just take it out raw.

**Comment by gildor2** [comment]
There's a separate issue discussing OPUS sounds - https://github.com/gildor2/UModel/issues/43
At the moment I'm not planning saving "UE4OPUS" files because there's no such format exists.

**Comment by bnnm** [comment]
I really hope you reconsider. UE4OPUS is indeed a real format (*not* raw/meaningless data), no different than Ogg Opus, WAV, MP3, or any other audio file.
It has a clear header, data packets, and looks like any audio format, and is perfectly extractable from UE4 uasset/uexp/etc. It's simply a new format that Epic made up, this is common among game devs.

Note that "Opus" is an audio codec. "Ogg" is a format container that can has audio codec data like Opus (or Vorbis). Similarly UE4OPUS is a container, with Opus codec data.

Ogg (the container) is inefficient and not well designed for games, so clever devs don't use it directly but create custom optimized formats (example: Switch Opus, EA Opus, etc), that aren't any less real than Ogg Opus.

It's similar to this: Windows uses .WAV, a container that can hold PCM data. Mac instead uses .AIFF, another container that also holds PCM data. WAV may be more common, but AIFF isn't any less real that WAV.
If you want to convert UE4OPUS to Ogg Opus to make it easier to play, ok, but that's no different that converting AIFF into WAV.

**Comment by gildor2** [comment]
Well, I've added export of UE$OPUS files. Please check if it works for you.

**Comment by Khodyn** [comment]
Works, I can then use vgmstream to convert it to a wav. Thanks! 😄
