### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by mendax47** [gildor2/UModel#103]
Out of memory: failed to allocate 255488 bytes
appMalloc:size=255488 (total=1595 Mbytes) <- FArray::Empty:255488 x 1 <- TArray::SerializeSimple <- UAnimSequence4::Serialize <- LoadObject:AnimSequence4'leo_shotgun_mh.leo_shotgun_mh', pos=122E, ver=513/0 (unversioned), game=ue4.17 <- UObject::EndLoad <- LoadWholePackage:leo_shotgun_mh <- Load:6248/12380 <- CSkelMeshViewer::FindUE4Animations <- CSkelMeshViewer::AttachAnimSet <- UIMenuItem::HandleCommand <- UIMenuItem::HandleCommand <- CUmodelApp::WndProc <- VisualizerLoop <- Main:umodel_build=880

**Comment by gildor2** [comment]
Ask on the forum please, if nobody did that yet. May be other people has found some special settings which makes it working. May be, if engine updated, you'll just need to select different settings to open the game.
