### ISSUE TITLE
PSA/PSK Importer

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#105]
I try to import BNS Mesh and animation in the past I managed to import clearly with the animation to play 
but now after downloaded this updated one it's look like that
![wtf](https://user-images.githubusercontent.com/29927382/47528237-4eee9300-d8ad-11e8-9e6b-ae352c09b0e0.png)

Blade And Soul Jin Female Mesh with Jin Female Animation

**Comment by gildor2** [comment]
Show me this mesh and animation in UModel's viewer (screenshot of animated mesh).

**Comment by DemonRem** [comment]
you think
![1](https://user-images.githubusercontent.com/29927382/47538687-575ac400-d8d5-11e8-95e1-6907209db0c2.png)
![2](https://user-images.githubusercontent.com/29927382/47538689-575ac400-d8d5-11e8-8d86-7b6f12e8dc05.png)

**Comment by gildor2** [comment]
First screenshot shows nothing. Second, I think, shows the mesh which you're saying is "bad", however I asked you to play animation in UModel - you didn't do that. So, it's rather useless for me.

**Comment by DemonRem** [comment]
how I doing it?

**Comment by gildor2** [comment]
Well, you should check tutorials then. If you don't know how to use umodel, then it's quite possible that you're doing something wrong - and then opening "issues" here,

**Comment by DemonRem** [comment]
ok I check and let you know thank anyway @gildor2
