### ISSUE TITLE
when bash build.sh,error:visual C++ is not found(the vs is vs2017)

### ISSUE THREAD

**Issue by optimalSolution-Q** [gildor2/UModel#107]
when I build the source,bash build.sh, output the error:visual C++ is not found, the vision of Visual Studio is  Visual Studio 2017 ,I am sure the VC is ok.

**Comment by gildor2** [comment]
What's your VS location? Did you install it into your "Program Files"? Do you have
Program Files/Microsoft Visual Studio/Installer/vswhere.exe

**Comment by optimalSolution-Q** [comment]
I use the vs 2017 Community, the path about vs is "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe", and I also had tried to modify the "CheckVC "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC" 15 2017	# 15.0" or tried chance the variable about "progs" in vc32tools, but it isn't work.
![image](https://user-images.githubusercontent.com/41374112/48195660-38573a00-e38b-11e8-98f8-79d11b97c8bd.png)

how to modify the "CheckVC" or "progs"

**Comment by gildor2** [comment]
Did you solve the issue? If yes, what was wrong then?
I just have older version of VS2017 and can't update it soon without affecting my work so much. That's why I wasn't able to check with recent VS to be sure that it should work.
