### ISSUE TITLE
How are TFC Offsets Calculated

### ISSUE THREAD

**Issue by lowlines** [gildor2/UModel#11]
I'm trying to add support for custom TFC formats not currently supported by umodel, and it has gotten me examining how standard TFCs/Texture2Ds work so I can get a better understanding of what I should be looking for in the custom implementation. I have looked over this github many times but I cannot for the life of me see how you take a Texture2D serialized object and translate that into a file offset into a TFC file. I understand that TFCs are concatenated LZO blocks that correspond to raw texture data (and in newer versions they are prepended with a header that begins with 0xDD7478BB), but I can't see how to point correctly to these as they don't seem to line up with anything from the Texture2D.

Can you please explain how this is being done and point me to the relevant source code?

**Comment by gildor2** [comment]
Take a look at UTexture2D::LoadBulkTexture().
Data pointers are in "Bulk" structure, serialized at the end of function, with calls to

`Bulk->SerializeData(*Ar);`

However bulk doesn't know about file where data stored, and the remaining part of LoadBulkTexture function finds which file to use.

**Comment by lowlines** [comment]
Ah so bulk data is the raw data at the end of an UnObject. Is there documentation anywhere on the bulk data format? I have figured out where the offsets are though.

It looks like my Texture2D have no bulk data when it is being stored in the custom TFC file. Texture2Ds with the texture data embedded have a 0x35 byte block and then variable size block that begins with 0xDD7478BB and finally the raw texture data. Is this a non-standard bulk data format as it looks completely different to Texture2D bulk data from a game that umodel supports. The custom TFC has these bulk data blocks but laid out differently.

**Comment by gildor2** [comment]
Here you may find the best documentation ever for UE3 data formats (specialized to Blade & Soul, but this doesn't amtter)
https://sites.google.com/site/sippeyfunlabs/blade-and-soul-a-unreal-3-based-game-mod-section
(of course, this is third-party, not Epic's documentation)

Regarding "no bulk data" - higher mips can be without bulk data if these mips are stripped.
