### ISSUE TITLE
Opening Skeletal Meshes from Unreal Engine 4 games crashes umodel

### ISSUE THREAD

**Issue by MartinBFFan** [gildor2/UModel#112]
Everytime I attempt to open or export a skeletal mesh from an UE4 game directly from the paks, I get the following error and then the umodel crashes:

Skeleton::Serialize(UE4_Mannequin_Skeleton): 2 unread bytes
LoadObject:Skeleton'UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton', pos=31C5, ver=516/0 (unversioned), game=ue4.21 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- CUmodelApp::ProcessKey:key=6F, down=1 <- VisualizerLoop <- Main:umodel_build=898

This happens only with Unreal Engine 4. Previous versions of Unreal Engine (3,2, 1 etc.) do not have that problem.

**Comment by gildor2** [comment]
There are many UE4 games, and many UE4 versions. Every version differs. You're using 4.21, which is not fully supported yet.

**Comment by MartinBFFan** [comment]
Oh. Thanks for notifying me.

**Comment by gildor2** [comment]
Strange issue. Closing.
