### ISSUE TITLE
Please Help I have tried Umodel V4.19 and V4.21

### ISSUE THREAD

**Issue by Awadoy** [gildor2/UModel#117]
ERROR: Skeleton::Serialize(F_MED_Plague_Skeleton): 2 unread bytes
LoadObject:Skeleton'F_MED_Plague_Skeleton.F_MED_Plague_Skeleton', pos=67AD, ver=516/0 (unversioned), game=ue4.21 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_build=898

THIS IS WHAT I GET PLEASE HELP?!

**Comment by gildor2** [comment]
Have you read [that](https://github.com/gildor2/UModel/issues/113)?

**Comment by Awadoy** [comment]
Yes I did and found nothing regarding m question I respect your time, but this is an issue that I didn't find in any of the forums that's why I'm asking you sir.

**Comment by gildor2** [comment]
You should use custom umodel build to open new Fortnite. The link is in the Fortnite thread, check it from the bottom.
