### ISSUE TITLE
Is this a mistake in Core.h?

### ISSUE THREAD

**Issue by SheilaLundin** [gildor2/UModel#119]
`#	ifndef WINAPI		// detect <windows.h>
	extern "C" {
		__declspec(dllimport) unsigned long __stdcall GetTickCount();
	}
#	endif`
Should "ifndef" be "ifdef"?

**Comment by gildor2** [comment]
Which compiler did you use? Which error did it show?

**Comment by gildor2** [comment]
I think I've fixed the issue. I suppose you tried to build extractor or decompressor, those were failed to build for me as well.
