### ISSUE TITLE
BaseBPs .uasset files 

### ISSUE THREAD

**Issue by HeresHavi** [gildor2/UModel#121]
Hey there,

I'm trying to export the .uasset files that are under the folder BaseBPs to get information regarding an item. Is there are a way to export it?

![image](https://user-images.githubusercontent.com/39027816/51703759-7f161100-2017-11e9-9839-077dbce5593a.png)

**Comment by gildor2** [comment]
It doesn't matter which name folder has. It matters what's inside. It is known that umodel exports only graphical assets and sounds.

**Comment by HeresHavi** [comment]
Ah, yeah that makes sense. I was just saying that because I didn't really know how to write this down. But yeah basically my question was if I was able to export Data for items. Will this be supported in the future or no plans for this? 

Also, since we are talking about this, maybe an idea to support LOCRES in the future. Now I have to use an external program to export these files.

**Comment by gildor2** [comment]
I have no plans for data table export, sorry. And I'm absolutely unfamiliar with LOCRES data formats.

**Comment by HeresHavi** [comment]
The program that I use to export .LOCRES files has a src file, maybe u could look how it's done and maybe look into it if you'd like of course. 

https://pastebin.com/zzDX0yqx - Binary
https://pastebin.com/Rky0RvfT - Import
