### ISSUE TITLE
Unmodel issue....

### ISSUE THREAD

**Issue by RitickSaha** [gildor2/UModel#124]
while i was extracting PUBG mobile made on unreal engine 4 Mostly all files gets unmodeled but when i started to unmodel static mesh of buildings the application crashed and said bad memory allocation i tried every version of UE1/UE2/UE3 and UE4. I litraly extracted whole game file except the Buildings... help me out with the same!

**Comment by gildor2** [comment]
Ask on the forum (in [PUBG Mobile thread](http://www.gildor.org/smf/index.php/topic,6073.0.html)) please. May be the issue is already there, and may be someone already solved it.
The Issue board on github is for something else, not about compatibility with games.

**Comment by RitickSaha** [comment]
I didn't found related one.. actually it is mostly  related  unmodel software.. that why it is saying bad memory allocation even if more than half of the files are unmoled by UE 4.18 version?

**Comment by gildor2** [comment]
Crash usually means that settings are wrong or game is not supported.
