### ISSUE TITLE
Dauntless preset definition seems outdated

### ISSUE THREAD

**Issue by Ovahlord** [gildor2/UModel#125]
rev.: 9c3ffa318a63b6f799e6c9ddaf2d2f9146dbb691

It appears that the preset for the Dauntless settings is outdated as it can load the uasset files but no actual files. Afaik the current dauntless game client is using v5 encryption and seems to be running on UE version 4.20.3.0.
According to the table of supported games the current build is expected to be running on 4.19 which no longer seems to be the case. I don't have a exact date when they have updated the engine or encryption version but it seems to have happened a few patches ago. Since it's a live service game, grabbing a older client is not possible to diff the builds.
I might try my part to get things working again if I can get instructions how to contribute.

**Comment by gildor2** [comment]
Everything related to Dauntless is done based on this discussion:
http://www.gildor.org/smf/index.php/topic,6184.msg32053.html#msg32053

And in UModel it uses 4.20 engine. Table - I'm rarely updating it. Just did an update.

Here's the commit which did all the changes.
https://github.com/gildor2/UModel/commit/9a11a754d6c6cc6588ca76324ec74650aa66a35c

**Comment by Ovahlord** [comment]
Allright, thank you. I will investigate and try to find out why some files are missing then, specifically naming the music sound files and behemoth skeletons. Might be related to the update last week but I will try to pinpoint the issue.

**Comment by Ovahlord** [comment]
Ye, so apparently it appears the exporter has a bug as it cannot export any file. Judging the package loading output it seems the exporter fails to read the engine version so this explains while no audio file or anything else is getting exported.

**Comment by gildor2** [comment]
Only "loader" bothers about engine version, not "exporter". If would be nice if you'd show me what you're doing, or send a few "saved" files (those ones which has a mesh or something exportable) from the game so I'd try myself.

**Comment by Ovahlord** [comment]
I just loaded the game files, scanned content and tested the output by selecting all assets from the /Game/Audio directory and hitting export. The specified output directory however remains empty which has led me to my conclusion. I did some further tests with icons and they seem to work fine while the audio assets remain inaccessible.

**Comment by gildor2** [comment]
First of all, it is not confirmed on the forum that sounds works for this game. Second, you probably didn't activate sound loading.

**Comment by Ovahlord** [comment]
Allright, thanks for the info. I will pick up forum posts first for the next reports if I find any. I had the sounds argument enabled though so ye, it appears to be confirmed then that sounds do not work at the moment. Sorry for wasting your time.

**Comment by gildor2** [comment]
If umodel didn't crash when trying to load sounds (with -sounds option), then most likely this game uses custom sound system which is not recognized by umodel.

**Comment by Ovahlord** [comment]
Yes, I remember one of the Dauntless Sound developers was talking about using a all new sound system. It's quite a surprise though that they actually changed the entire structure for that then.
