### ISSUE TITLE
Umodel Problem

### ISSUE THREAD

**Issue by ItsGohma** [gildor2/UModel#126]
Everytime I try to press ok after choosing where I have my pak files at, and the unreal engine version, etc. I get this and nothing shows up. Is there something I'm doing wrong? It legit won't even give me a chance to put in an aes at all.
![Screenshot (26)](https://user-images.githubusercontent.com/49521037/55954405-3cca9c00-5c24-11e9-9f37-33068d2f7cb4.png)

**Comment by gildor2** [comment]
https://github.com/gildor2/UModel/issues/113
http://www.gildor.org/smf/index.php/topic,3317.1320.html

**Comment by ItsGohma** [comment]
I apologize, I just randomly stumbled upon the github browsing through
google trying to find a fix.

**Comment by okudan07** [comment]
same here

**Comment by okudan07** [comment]
i have the same issue
