### ISSUE TITLE
SDL2.dll not found

### ISSUE THREAD

**Issue by Aerthas** [gildor2/UModel#127]
Upon updating a previous version using TortoiseSVN (as have always done), this error code came up whenever attempting to launch umodel.exe. Deleting the files and re-downloading does not solve the issue. 
Using the older version off the "Gildor's Homepage" does not receive this issue.
Using the commit [eb2fbd459ab16cb495370713cdce011dc7555aea](https://github.com/gildor2/UModel/tree/eb2fbd459ab16cb495370713cdce011dc7555aea) does not receive this issue.
Using the commit [fd75e49d91c79c9c6dec5d7a930068f88f48f004](https://github.com/gildor2/UModel/tree/fd75e49d91c79c9c6dec5d7a930068f88f48f004) does not receive this issue.
Using the commit [7c969ce8e1ad8937fcfe67fc2e90ce6843cbc23e](https://github.com/gildor2/UModel/tree/7c969ce8e1ad8937fcfe67fc2e90ce6843cbc23e) DOES receive this issue.

Exact error code is as follows:
umodel.exe - System Error
The code execution cannot proceed because SDL2.dll was not found. Reinstalling the program may fix this problem.
![image](https://user-images.githubusercontent.com/25449461/57251419-5981a600-700f-11e9-9a32-1218e7fe5828.png)

Exact URL used for TortoiseSVN is as follows:
https://github.com/gildor2/UModel.git/trunk

Windows version:
Windows 10 Pro 64-bit (10.0, Build 17134)

**Comment by gildor2** [comment]
I've put sdl2.dll to libs/sdl2/[x86|x64]. When you're running build.sh, it will copy 32 or 64 bit dll (depending on build command) next to umodel.exe.
