### ISSUE TITLE
I cant build umodel 64bit for windows ?

### ISSUE THREAD

**Issue by MiriDevAndro** [gildor2/UModel#128]
I cant build umodel 64bit for windows it have just for linux platform ? Help

**Comment by gildor2** [comment]
Check readme.md, I've wrote very descriptive instructions there.

**Comment by MiriDevAndro** [comment]
this is error display in cmd

Generating makefile from UmodelTool/umodel.project ...
Gathering dependency info ...
Makefile generated.
make: Nothing to be done for 'ALL'.

**Comment by gildor2** [comment]
How do you run build process?

**Comment by MiriDevAndro** [comment]
with bash from cmd

**Comment by MiriDevAndro** [comment]
does problem show because of visual studio 2019 preview ?

**Comment by MiriDevAndro** [comment]
and this errors 

/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
/usr/bin/vc32tools: line 16: [: latest: integer expression expected
/usr/bin/vc32tools: line 20: [: latest: integer expression expected
ERROR: Visual C++ is not found.

**Comment by gildor2** [comment]
I think you're using OLD "vc32tools", because recent one don't have anything in lines 16 and 20.

**Comment by MiriDevAndro** [comment]
you have right but now i get just this error 

ERROR: Visual C++ is not found.

i have installed visual studio 2017 now

**Comment by gildor2** [comment]
Visual Studio should be found if it is installed into Program Files. If not, you should adjust vc32tools with correct location. UModel could be build with VS 2015, 2017 or 2019.

**Comment by MiriDevAndro** [comment]
and last error i think 

PackageScanDialog.cpp
ProgressDialog.cpp
SettingsDialog.cpp
StartupDialog.cpp
UmodelApp.cpp
UmodelCommands.cpp
UmodelSettings.cpp
'rc.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MiriDevAndro** [comment]
thnx a lot i have fix all errors

**Comment by gildor2** [comment]
Great.
