### ISSUE TITLE
Error when trying to extract file from game.

### ISSUE THREAD

**Issue by yegoD1** [gildor2/UModel#130]
I want to try and be able to extract 3D models from the game DEATHGARDEN but I come up with this error every time,
`lzxd_decompress(1584,3480) returned 11
appDecompressLZX <- appDecompress:CompSize=1584 UncompSize=3480 Flags=0x4 <- SerializeCompressed <- FPakFile::Serialize:file=/Game/ECGameSingletonBP.uasset <- FArchive::ByteOrderSerialize <- UnPackage::CreateLoader:/Game/ECGameSingletonBP.uasset <- UnPackage::UnPackage:/Game/ECGameSingletonBP.uasset, ver=100000/0, game=0 <- UnPackage::LoadPackage:/Game/ECGameSingletonBP.uasset <- CUmodelApp::ShowPackageUI <- Main:umodel_build=1021`
Can you please add support?

**Comment by gildor2** [comment]
Did you tell it "xbox360" or "lzx" option? I see there's something wrong with your startup settings. UE4 games never use LZX, but umodel crashes trying to decompress LZX block.

**Comment by FunGamesLeaks** [comment]
For Fortnite I remember that Umodel crashed with the same error message on Oodle compressed paks because they Oodle also uses 4 as compression method

**Comment by yegoD1** [comment]
I changed the compression method, still no success, came up with the same error,
`lzxd_decompress(3020,6915) returned 11
appDecompressLZX <- appDecompress:CompSize=3020 UncompSize=6915 Flags=0x4 <- SerializeCompressed <- FPakFile::Serialize:file=/Game/Characters/Hunter/Models/Shaman/Meshes/Head/HT_SHAMAN_Head_Prog001.uasset <- FArchive::ByteOrderSerialize <- UnPackage::CreateLoader:/Game/Characters/Hunter/Models/Shaman/Meshes/Head/HT_SHAMAN_Head_Prog001.uasset <- UnPackage::UnPackage:/Game/Characters/Hunter/Models/Shaman/Meshes/Head/HT_SHAMAN_Head_Prog001.uasset, ver=100000/0, game=0 <- UnPackage::LoadPackage:/Game/Characters/Hunter/Models/Shaman/Meshes/Head/HT_SHAMAN_Head_Prog001.uasset <- CUmodelApp::ShowPackageUI <- Main:umodel_build=1021`

**Comment by gildor2** [comment]
There should be "default" compression method, you shouldn't set it. If "default" says exact error message from your first message, then this game uses custom compression method, just like @FunGamesLeaks says. No idea about "oodle" or anything else, and usually custom compression method in UE4 encoded with code 0x10, not 4.

**Comment by gildor2** [comment]
But anyway, I do not welcome posting game-specific questions on github, I even made a "sticky issue" about it, it's on the top of "issues" page. This game has a thread on the forum, and similar questions should be asked THERE, because you'd be able to get help from other people, not just me.
