### ISSUE TITLE
Fatal Error when loading a .upk

### ISSUE THREAD

**Issue by MailBoxSNES** [gildor2/UModel#131]
i need help when ever i open a .upk that has meshes i this error message

RawArray item size mismatch: expected 12, serialized 16

SerializeBulkArray <- FRawAnimSequenceTrack<< <- TArray::Serialize:1/70 <- UAnimSequence::Serialize <- LoadObject:AnimSequence'HatInTime_Characters_HatKid.AnimSequence_126', pos=9CEAD7, ver=888/5, game=ue3 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_build=1018

**Comment by gildor2** [comment]
Find the thread about this game on the forum and read it. If no thread, then the game is not supported.

https://github.com/gildor2/UModel/issues/113
