### ISSUE TITLE
Umodel does not ask for an aes key

### ISSUE THREAD

**Issue by MrMuffin64** [gildor2/UModel#133]
I was using umodel for fortnite and when I opened the program it didn't say anything about the AES key, it just takes me to a screen that says "all packages"
![umodel](https://user-images.githubusercontent.com/53883712/62667022-1eab4900-b943-11e9-984a-693fe89de5d6.PNG)

when I press ok it takes me to this
![umodel not working](https://user-images.githubusercontent.com/53883712/62667034-2a970b00-b943-11e9-8bf0-ca5dc99da916.PNG)

**Comment by Blenux** [comment]
Github isn't a place to ask this, the forums are.

[Gildor Forums](https://www.gildor.org/smf/index.php/topic,3317.1365.html)

**Comment by MrMuffin64** [comment]
I asked, no one even replied

**Comment by Blenux** [comment]
Replied....

**Comment by gildor2** [comment]
"Nobody replied" means - "I expected whole 5 MINUTES at deep night and nobody woke up and answered my question"??

Man, if UI window is empty, you had to look at SECOND window. You're at github, so you SHOULD know what "console window" is and why it ever exists.
