### ISSUE TITLE
Error reading Advent Rising filesystem

### ISSUE THREAD

**Issue by einstein95** [gildor2/UModel#2]
G:\SteamLibrary\SteamApps\common\Advent Rising\textures>umodel.exe skyboxes_tx.utx
Found 24 game files (3 skipped)
Loading package: skyboxes_tx.utx Ver: 145/61447 Names: 207 Exports: 151 Imports: 14 Game: 2000
******** skyboxes_tx.utx ********
*** ERROR: Serialized FString is not null-terminated
FString<< <- Name:0 <- ReadNameTable <- UnPackage::UnPackage:skyboxes_tx.utx, ver=145/61447, game=2000 <- UnPackage::LoadPackage:skyboxes_tx.utx <- Main:umodel_version=341

G:\SteamLibrary\SteamApps\common\Advent Rising\staticmeshes>umodel.exe aurelianarchitecture_sm.usx
Found 11 game files (2 skipped)
Loading package: aurelianarchitecture_sm.usx Ver: 146/61447 Names: 260 Exports: 208 Imports: 56 Game: 2000
******** aurelianarchitecture_sm.usx ********
*** ERROR: Serialized FString is not null-terminated
FString<< <- Name:0 <- ReadNameTable <- UnPackage::UnPackage:aurelianarchitecture_sm.usx, ver=146/61447, game=2000 <- UnPackage::LoadPackage:aurelianarchitecture_sm.usx <- Main:umodel_version=341

Any utx or usx file (except for one test_tx.utx file) give this error on loading.

Example utx file: http://puu.sh/ham8b/01ffff68e0.utx

**Comment by gildor2** [comment]
This game is not supported (check the [Compatibility Table](http://www.gildor.org/projects/umodel/compat)). It uses UE2.X, and really only one game is supported with this engine - Unreal Championship 2. There's too much mess with this engine.

**Comment by einstein95** [comment]
Ah, fair enough.
