### ISSUE TITLE
Batman: Arkham Origins wrong name index errors

### ISSUE THREAD

**Issue by Kjasi** [gildor2/UModel#20]
I started exporting files from Arkham Origins (PC, via Steam) and I'm getting a lot of "wrong name index" errors. Example error:
`Package "Online/BmGame/CookedPCConsole/Startup.upk": wrong name index -16777216
UnPackage::SerializeFName:pos=0005BF01 <- SerializeObjectExport3 <- UnPackage::LoadExportTable <- UnPackage::UnPackage:Online/BmGame/CookedPCConsole/Startup.upk, ver=807/104, game=8000 <- UnPackage::LoadPackage:startup_xxx <- UnPackage::CreateImport:SinglePlayer/BMGame/CookedPCConsole/FALCONE_StrArch_SF.upk:33 <- UnPackage::SerializeUObject <- TArray::Serialize:0/4 <- SerializeFMaterialResource <- LoadObject:Material3'FALCONE_StrArch_SF.Eye_Mat', pos=46AED, ver=807/138, game=8014 <- UObject::EndLoad <- LoadWholePackage:FALCONE_StrArch_SF <- CUmodelApp::ShowPackageUI <- Main:umodel_version=522`

Here's what the commandline says for the same error:
`Found 3310 game files (6402 skipped)
Loading package: SinglePlayer/BMGame/CookedPCConsole/FALCONE_StrArch_SF.upk Ver: 807/138 Engine: 10122 Names: 576 Exports: 294 Imports: 44 Game: 8014
Memory: allocated 2018679 bytes in 3357 blocks
Loading Material3 Eye_Mat from package SinglePlayer/BMGame/CookedPCConsole/FALCONE_StrArch_SF.upk
WARNING: BoolProperty "UMaterial3::bSpecularBlinnPhong" was not found
WARNING: BoolProperty "UMaterial3::bSpecularConserveEnergy" was not found
WARNING: BoolProperty "UMaterial3::bSpecularMaskByShading" was not found
WARNING: StructProperty "UMaterial3::CustomAmbientAttenuationColor" was not found
WARNING: StructProperty "UMaterial3::AnisotropicDirection" was not found
WARNING: ArrayProperty "UMaterial3::MaterialFunctionInfos" was not found
Loading package: Online/BmGame/CookedPCConsole/Startup.upk Ver: 807/104 Engine: 7748 Names: 484 Exports: 298 Imports: 47 Game: 8000
******** Loading object Material3'FALCONE_StrArch_SF.Eye_Mat' ********
*** ERROR: Package "Online/BmGame/CookedPCConsole/Startup.upk": wrong name index -16777216
UnPackage::SerializeFName:pos=0005BF01 <- SerializeObjectExport3 <- UnPackage::LoadExportTable <- UnPackage::UnPackage:Online/BmGame/CookedPCConsole/Startup.upk, ver=807/104, game=8000 <- UnPackage::LoadPackage:startup_xxx <- UnPackage::CreateImport:SinglePlayer/BMGame/CookedPCConsole/FALCONE_StrArch_SF.upk:33 <- UnPackage::SerializeUObject <- TArray::Serialize:0/4 <- SerializeFMaterialResource <- LoadObject:Material3'FALCONE_StrArch_SF.Eye_Mat', pos=46AED, ver=807/138, game=8014 <- UObject::EndLoad <- LoadWholePackage:FALCONE_StrArch_SF <- CUmodelApp::ShowPackageUI <- Main:umodel_version=522`

Hopefully, fixing this will also fix the serialization errors I've been seeing in the batch export:
`Found 3310 game files (6402 skipped)
Loading package: Online/BmGame/CookedPCConsole/AkAudio.upk Ver: 807/104 Engine: 7748 Names: 394 Exports: 289 Imports: 85 Game: 8000
******** D:\SteamLibrary\steamapps\common\Batman Arkham Origins\Online\BmGame\CookedPCConsole\AkAudio.upk ********
*** ERROR: Unable to serialize 6482 bytes at pos=0x40E7
FFileReader::Serialize:File=AkAudio.upk <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- TArray::SerializeSimple <- SerializeObjectExport3 <- UnPackage::LoadExportTable <- UnPackage::UnPackage:Online/BmGame/CookedPCConsole/AkAudio.upk, ver=807/104, game=8000 <- UnPackage::LoadPackage:Online/BmGame/CookedPCConsole/AkAudio.upk <- Main:umodel_version=522`

Hopefully this will help you find the issue and resolve it quickly! Let me know if you need more info!

**Comment by gildor2** [comment]
I see you're using wrong path to the game. Online and Singleplayer packages are mixed together,
