### ISSUE TITLE
getting lzxd_decompress(26722, 131072) returned 11 when attempting to open Devil's Third Wii U files

### ISSUE THREAD

**Issue by KekMcGee** [gildor2/UModel#21]
Here's the error 

appDecompressLZX <- appDecompress:CompSize=26722 UncompSize=131072 Flags=0x4 <- DecompressBlock:block=740+6862 <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- FArchive::ByteOrderSerialize <- FPackageFileSummary<<:Ver=0/0 <- UnPackage::UnPackage:CookedWiiU/Startup.xxx, ver=100000/0, game=0 <- UnPackage::LoadPackage:startup_xxx <- UnPackage::CreateImport:CookedWiiU/CharacterCheckStage_Evil.xxx:86 <- UnPackage::SerializeUObject <- TArray::Serialize:0/1 <- SerializeFMaterialResource <- LoadObject:Material3'CharacterCheckStage_Evil.MasterShader_Masked', pos=2BF37, ver=868/1, game=804A <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_version=521

**Comment by gildor2** [comment]
1. WiiU games can't use "LZX" compression method, because this compression is XBox360-only.
2. I'm not sure if you'll be able to open WiiU version of this game. Check gildor.org forums to fins answers to your possible questions.
