### ISSUE TITLE
paragon 20160124 version can not extract any anim

### ISSUE THREAD

**Issue by gcclua** [gildor2/UModel#22]
Hi,Konstantin Nosov
    thank you make the great tool, I try the 
    paragon 20170124 version can not extract any hero's anim, either texture , 
    the static mesh is ok

**Comment by gildor2** [comment]
Hi.
I've updated PARAGON game, and the game works exactly the same like before the game update - I can open everything except some animations. Probably you didn't update your UModel? What error message do you have?
