### ISSUE TITLE
ERROR: Memory: bad allocation size -18783732 bytes

### ISSUE THREAD

**Issue by Unicorn808** [gildor2/UModel#23]
So, uh, just downloaded the tool, ran it from the directory the upk file is in, selected the file, clicked export, and then this happened. What am I doing wrong/how could I fix it so I can extract the upk? Is it because the game isn't supported? If so, I should find out the version of UDK it uses and then try again?

> Memory: bad allocation size -18783732 bytes
> appMalloc:size=-18783732 (total=6 Mbytes) <- FArray::Empty:1072176513 x 12 <- SerializePackageFileSummary3 <- FPackageFileSummary<<:Ver=687/115 <- UnPackage::UnPackage:DD2_SpookyForest02.upk, ver=687/115, game=8000 <- UnPackage::LoadPackage:DD2_SpookyForest02.upk <- CUmodelApp::ShowPackageUI <- Main:umodel_version=553

(If this isn't a real issue, my bad, and please point me in the right direction to a place where I can get my question answered)

**Comment by gildor2** [comment]
What's the game?

**Comment by gildor2** [comment]
I think this is Dungeon Defenders 2, isn't it?
http://www.gildor.org/smf/index.php/topic,2648.0.html
The recent version of this game is not supported.

**Comment by Unicorn808** [comment]
Yup, that is the game. Because it isn't supported, does that mean there is no way to unpack those files?

**Comment by gildor2** [comment]
UModel worked with older version of this game. New version is not supported, so you can't use UModel to extract or view content.
Just for your information: version could be found in log, in your first message it is "ver=687/115".

**Comment by Unicorn808** [comment]
Oh well. In any case, thanks for your help!
