### ISSUE TITLE
VS 2015 build error

### ISSUE THREAD

**Issue by brendancboyle** [gildor2/UModel#24]
Hi Gildor,

I'm trying to get UModel to build under VS 2015 and I am getting the following errors. I am running the latest Windows 10 Pro build with VS 2015 Update 3. When I use the provided MinGW bash build tools, I get an error related to locating the OpenGL header: "UModel\Core\CoreGL.h(8) : fatal error C1083: Cannot open include file: 'GL/gl.h': No such file or directory" (see full log below). I then decided to use NMake to build the project, and was able to successfully build the zipped source code from November with only slight modifications (double declaration of macro in the nvtt lib which I commented out to fix, I also had to rebuild SDL2 to support VS2015). However, when I tried to build the master branch, I get the following error: "UI/FileControls.cpp(262): error C2280: 'FString::FString(const FString &)': attempting to reference a deleted function
C:\Users\brend\OneDrive\Documents\GitHub\UModel\Unreal\UnCore.h(2017): note: compiler has generated 'FString::FString' here" (see full log below)." If you could provide any assistance that would be greatly appreciated.

Update: I can build it fine using Ubuntu and make so there is nothing wrong with my source. I just need help getting nmake to build it

Thanks!
Brendan

Bash build:

Will post as soon as AWS outage stops

NMake build:

Will post as soon as AWS outage stops

**Comment by gildor2** [comment]
Hi Brendan,

I'll check this ASAP (but do not expect anything in next 8 hours - it's very late here now ...) There are number of problems with VS2015 (with my build tools), so I can't do this quickly.

I'm using VS2010 for building UModel. Recent gcc also works well.

Thanks,
Konstantin

**Comment by brendancboyle** [comment]
No worries at all, take your time. I really appreciate that you still maintain this project. It's a great tool!

Thanks,
Brendan

**Comment by gildor2** [comment]
Hi Brendan,

I've fixed VS2015 build issues. See today's commits to git repository.

Thanks,
Konstantin

**Comment by brendancboyle** [comment]
Hi Konstantin,

Thank you so much for the help! I was able to successfully build the project with NMake and MinGW Bash. I'm going to open one additional issue describing a separate build tool bug I found, but this patch cleared everything else up.

Thanks,
Brendan
