### ISSUE TITLE
Original Dungeon Defenders unable to open startup upk's skeletal meshes

### ISSUE THREAD

**Issue by KekMcGee** [gildor2/UModel#26]
I've tried this with and without the dlc installed.

I've been looking to grab the player models for ages, I assume they are in here as I've looked through every other UPK for them.

Without overriding game detection.

assertion failed: w > 0 & w < 256

ProcessVerts <- ConvertLod:lod=0 <- USkeletalMesh3::ConvertMesh <- USkeletalMesh3::PostLoad <- PostLoad:SwordOfEmbers_SK <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_version=569

and with overriding game detection.

Memory: bad allocation size - 1058928224 bytes

call stack:
appMalloc:size=-1058928224 (total=1 Mbytes) <- FArray::Empty:202252442 x 16 <- TArray::Serialize:0/0 <- SerializePackageFileSummary3 <- FPackageFileSummary<<:Ver=678/2 <- UnPackage::UnPackage:UDKGame/CookedPCConsole/Startup_ESN.upk, ver=678/2, game=dundef <- UnPackage::LoadPackage:UDKGame/CookedPCConsole/Startup_ESN.upk <- CUmodelApp::ShowPackageUI <- Main:umodel_version=569

If needed here's the startup upk with the game's exe.

https://mega.nz/#!Vlg1wS6L!qHrr5fYLXpF1ok1a_Kiw3BdI0WkQI--VQ4N9x5qkwNg

**Comment by gildor2** [comment]
I've fixed the issue. Now meshes in provided package are opened well. Don't use any game override, just open the file with new umodel.

**Comment by KekMcGee** [comment]
Thanks, works like a charm now.
