### ISSUE TITLE
[Unsupported] Paladins: Champions of the Realm

### ISSUE THREAD

**Issue by highattack30** [gildor2/UModel#27]
i understand that Paladins unsupported by UModel since i dont see this video game at the software

**Comment by gildor2** [comment]
1. This game has 2 threads on the forum (English and Russian).
http://www.gildor.org/smf/index.php/topic,2981.0.html
http://www.gildor.org/smf/index.php/topic,3007.0.html

2. The game is in "Early access" - http://store.steampowered.com/app/444090/Paladins/
I'm rarely dealing with games in "alpha" or "beta" stage, only with outstanding ones.

3. "Github issues" are not a good place to ask your questions.
