### ISSUE TITLE
Vita support.

### ISSUE THREAD

**Issue by indexftw** [gildor2/UModel#28]
Hi.
Any chances of ps vita support? Setting everything to auto while selecting content type ue3, Igau exports this https://puu.sh/w8RQ1/fc6ec652bb.jpg
Cheers.

**Comment by gildor2** [comment]
Hi.
How many UE3 Vita games do you know?

**Comment by indexftw** [comment]
On top of my head like 3 aaa titles like AC, BL2, and IGAU. I'm interested in IGAU personally as I have it on both pc and vita. But a quick google search while typing this resulted in a list a little more than that https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games

**Comment by gildor2** [comment]
There's no Vita exclusives there. Most of games has PC or Xbox360 support, and are already fully supported. I suppose "IGAU" is "Injustice" (had to google about that), and it works for PC, XBox360 and Android. Why doing anything for Vita?

**Comment by indexftw** [comment]
Thanks for the reply!
It is a capable system and recently, well almost a year a go it was jailbroken. As we have access to raw game files, modding took place and I thought it would be a good idea to speak from the community. That's all I got.

**Comment by gildor2** [comment]
Is there everything works except textures?

**Comment by indexftw** [comment]
Skeletal/static mesh options crash the program.

`appMalloc:size=1051595899 (total=0 Mbytes) <- FArray::Empty:1051595899 x 1 <- TArray::SerializeSimple <- UAnimSequence::Serialize <- LoadObject:AnimSequence'CHAR_KillerFrost.Clash_All', pos=15F5FA, ver=574/49, game=mk <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_version=590`

**Comment by gildor2** [comment]
Animation might not work. For MK series, it works only for Android and iOS games, and these games uses different version of UE3.

**Comment by indexftw** [comment]
I followed a page that suggested that I don't choose animation option. So I didn't. I tried different character files all would result in the same error. I guess they have same structure. I dunno why it crashed into `AnimSequence` but here's another one.
https://puu.sh/w9slr/81a2107d6e.png

`appMalloc:size=-1819071616 (total=0 Mbytes) <- FArray::Empty:1383228784 x 8 <- TArray::Serialize:0/0 <- FStaticLODModel3<< <- TArray::Serialize:0/1 <- USkeletalMesh3::Serialize <- LoadObject:SkeletalMesh3'CHAR_LexLuthor.LX_AssaultProbe_Sk', pos=93B561, ver=574/49, game=mk <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_version=590`

**Comment by gildor2** [comment]
Ok, so I'd say it is not supported.  Probably this platform uses some special format to store geometries in more compact form.

**Comment by indexftw** [comment]
Got it. Thanks for your time.
