### ISSUE TITLE
Tekken 7

### ISSUE THREAD

**Issue by highattack30** [gildor2/UModel#29]
I am sorry to disappoint you but seems like tekken 7 not support at all if they using customize data even this the tool would extract them as he doing in UE3 games so I would not call it full support maybe alpha but not full functional

**Comment by gildor2** [comment]
I'm sorry to disappoint you, but this game doesn't work only for you.
http://www.gildor.org/smf/index.php/topic,3220.msg22593.html#msg22593

**Comment by gildor2** [comment]
Tekken 7 is supported now
http://www.gildor.org/smf/index.php/topic,3220.0.html

Closing issue.
