### ISSUE TITLE
MKX support is not uploaded yet?

### ISSUE THREAD

**Issue by vorou** [gildor2/UModel#3]
The [latest commit](https://github.com/gildor2/UModel/commit/f9d4be2b5b63deb9ae289f91a552e9aecef673d0) says you've added the support for MKX, but I get this error with the latest binaries (`Updated 19 April, 2015 - 20:52`):

    appMalloc:size=808536909 <- FArray::Empty:808536909 x 1 <- FString<< <- SerializePackageFileSummary3 <- FPackageFileSummary<<:Ver=677/157 <- UnPackage::UnPackage:ui_c_buttonLib.xxx, ver=677/157, game=8000 <- UnPackage::LoadPackage:ui_c_buttonLib.xxx <- Main:umodel_version=345

Is it because you haven't updated the binaries on the site yet?

**Comment by gildor2** [comment]
Yes, UModel was outdated. I don't know how I missed that. Thanks.

**Comment by vorou** [comment]
You also forgot to update [the compatibility table](http://www.gildor.org/projects/umodel/compat), I guess.

**Comment by gildor2** [comment]
No, it's up to date. Only package format is supported now, but you can't load even textures. Only "decompress" and "extract" tools are working, UModel is quite useless for this game now.
