### ISSUE TITLE
Add ability to see "group" of assets

### ISSUE THREAD

**Issue by cmbasnett** [gildor2/UModel#31]
In UT2K4, there exists the concept of "groups" within Texture and StaticMesh packages. These are important in some cases to avoid ambiguities. There is currently no way to see these groups within Umodel. If you need an example I can provide one.

**Comment by gildor2** [comment]
Isn't "-groups" command line option what you're looking for?

**Comment by cmbasnett** [comment]
No, because this is an export-only option. I would like to be able to see the group name within the asset browser prior to export.

**Comment by gildor2** [comment]
Ok. Just give me examples of grouped assets for UT2K. I have the full game, so asset files are not needed.

**Comment by gildor2** [comment]
Added this feature - https://github.com/gildor2/UModel/commit/6a68e5bb7ced41842b7fc652a06fed2a0c63a574

**Comment by cmbasnett** [comment]
You're a hero mate. Sorry I don't have the UT2K4 files so I couldn't give
an example off the top of my head.
