### ISSUE TITLE
LawBreaker

### ISSUE THREAD

**Issue by highattack30** [gildor2/UModel#32]
lawbreaker now on his open beta and still can't open or export anything

**Comment by gildor2** [comment]
1. Why posting here, forum thread exists - http://www.gildor.org/smf/index.php/topic,3057.0.html
2. "Open beta" doesn't mean "should be supported by UModel". "Released" - this mean "may be supported".
3. The game will be available only August 8. I've downloaded it with Steam, but it is located in compressed form inside Steam/SteamApps/depotcache. In unusable form.

**Comment by gildor2** [comment]
It is fully supported now.
