### ISSUE TITLE
Allow exporting folders

### ISSUE THREAD

**Issue by xPaw** [gildor2/UModel#35]
It would be nice to be able to export folders (and their subfolders) in the explorer. As far as I can see, the export button becomes available only if files are selected in the right view.

**Comment by gildor2** [comment]
Do you mean - export action for folders, export everything what's in folder and subfolders?

**Comment by xPaw** [comment]
Ideally both.

**Comment by gildor2** [comment]
You may use flat view and filter to select packages from multiple folders.

**Comment by xPaw** [comment]
What about the tree view? I think it makes more sense to do it from there.

**Comment by gildor2** [comment]
Sure, but it's just a little bit complicated to do because UI framework used there developed by me, and it doesn't have necessary features at the moment.

**Comment by xPaw** [comment]
Something to consider for the future then.

**Comment by gildor2** [comment]
It is in plans, but I don't have free time to spend on umodel.

**Comment by gildor2** [comment]
Done with recent umodel.
