### ISSUE TITLE
WWE Immortals (Android) Unsupported Texture compresssion

### ISSUE THREAD

**Issue by KekMcGee** [gildor2/UModel#38]
ATI Texture Compression not supported. 

https://apkpure.com/wwe-immortals/com.wb.wwe.brawler2014

**Comment by gildor2** [comment]
Yes, ATI TC is not supported. This is normal situation - ATI didn't open-source their compression, so it is supported only by their libraries, which I'm not going to include into UModel. However Android games usually has a few data variants prepared for different platforms - with ETC, PVRTC or DXT compression - all of them ARE supported. Just find/download a different pack and open it with UModel.

**Comment by KekMcGee** [comment]
Ah, Alright thanks.
