### ISSUE TITLE
Proper materials?

### ISSUE THREAD

**Issue by Flandyn** [gildor2/UModel#39]
Will we eventually be able to open and view materials from UE4 games exactly as they appear in-game?
Maybe even import them back into UE4? I would like to get characters and maps from some games but right now i can't, since they use complex material functions which i cannot recreate.
If you want an example, take Paragon's materials.

**Comment by gildor2** [comment]
> Will we eventually be able to open and view materials from UE4 games exactly as they appear in-game?

It is very unlikely.

> Maybe even import them back into UE4?

In which format? Do you know how to import materials into UE4?

**Comment by Flandyn** [comment]
Well, i know you can export materials in .COPY or .T3D format, but I haven't tried importing any.

**Comment by gildor2** [comment]
.COPY is the same as .T3D I think. This is a volatile format, and it is supported in the engine only for export. As Epic said, this format is used for engine debugging purposes.

So, the only thing where you may create something "not by hands" in editor, is copy-paste. However, did you ever try to use it by yourself? It has very limited functionality for graph structures (blueprint, material etc). When I tried to copy part of blueprint from one project to another, I've got a large number of disconnected nodes, with partially filled node inputs/outputs. I had to setup and reconnect everything by hands, spent a day recovering things. And it is definitely not usable for research purposes.

In theory it is possible to show graph of material nodes in custom application like UModel, or may be adapt UE4 to load cooked materials in editor, but it is not possible to export it into one of formats, except perhaps as HLSL shader bytecode.
