### ISSUE TITLE
Tranfomers Online

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#40]
there will be any change that this game will support by umodel?

http://tfol.qq.com/main.shtml

**Comment by gildor2** [comment]
It seems the game is already supported?

http://www.gildor.org/smf/index.php/topic,3211.0.html

**Comment by DemonRem** [comment]
it's not reading the folder pak data
the engine used for that game is 4.14.3 as I choose the engine from the list 
this is the error I get

![tmerror](https://user-images.githubusercontent.com/29927382/34441789-ab2dfec2-ecc6-11e7-9d66-d838b7d2dab1.png)

**Comment by gildor2** [comment]
Did you decrypt pak files?

**Comment by DemonRem** [comment]
no with quickbms I can get few files of the uassest here is the script post in your forum by some member
[
[script.txt](https://github.com/gildor2/UModel/files/1593621/script.txt)
](url)

**Comment by gildor2** [comment]
Anyway, my tool works only after decryption process completion, and I can't help you with quickbms - I've never run it by myself.

**Comment by DemonRem** [comment]
huh well ok then
