### ISSUE TITLE
is this umodel error?

### ISSUE THREAD

**Issue by uragan1987** [gildor2/UModel#41]
Loading Texture2D eyepet_ball from package eyepet_ball.uasset
WARNING: StructProperty "UTexture2D::AlphaCoverageThresholds" was not found
  Skipping SourceArt: TSF_BGRA8, NumMips=1, Slices=1, PNGCompressed=1
******** eyepet_ball.uasset:  Texture2D'eyepet_ball' ********
*** Unknown texture format: PF_Unknown (0)
WARNING: Texture2D eyepet_ball has no valid mipmaps

----------------------------------------------------------

Hi all,
im really new at UE4 and try my first skills here, for a newby its a nice tool but for this error i cant find a solition
i have created a PNG (did try with TGA, same error), imported it to my project and saved,
after this opened UMODEL tool and did a check for my new created texture,
and i got this error,
duno why UMODEL show me PF_Unknown, on UE4 it shows PF_DXT5
is something wrong with compiler or UMODEL tool is buggy?

cya
uragan

**Comment by gildor2** [comment]
Hi
In UE4 DXT5 texture is stored in DerivedDataCache. Inside uasset, only PNG-compressed texture is stored. When you'll cook your project, DXT texture will go from DDC to uasset, replacing PNG texture.

**Comment by uragan1987** [comment]
wow you are really fast 👍 
will be nice to get this on error message
"Texture is not cooked"
