### ISSUE TITLE
Errors Opening Files

### ISSUE THREAD

**Issue by ShadowRanger** [gildor2/UModel#45]
For some reason whenever I try and open any model file in the latest version of UModel with any of the Unreal Engine versions, I get this error: Skeleton::Serialize(Dacia_A_01_New_Skeleton): 4 unread bytes
LoadObject:Skeleton'Dacia_A_01_New_Skeleton.Dacia_A_01_New_Skeleton', pos=354B, ver=514/0 (unversioned), game=ue4.18 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_version=646

I have gotten other errors as well such as bad memory allocation but it seems only with the latest version I'm getting these errors.

This is for the game PLAYER UNKNOWN's Battlegrounds by the way, which is meant to be supported by this program.

**Comment by gildor2** [comment]
First of all, I'd advice sending questions about particular games to the gildor.org forum. This is because there are 3 hundreds of games made with Unreal engine, and there are just 10-20 games of them which I'm checking by myself (mostly those ones which made by Epic Games). PUBG is not in my favorite list.

Here's the thread for this game:
http://www.gildor.org/smf/index.php/topic,3229.0.html

Regarding "latest version". Latest version of the game or of UModel? Why you're using 4.18 for this game?

**Comment by ShadowRanger** [comment]
I will respond to that thread to see if anyone knows why I'm getting errors. It was all fine until I updated to the very latest version of UModel. Prior to that, I didn't get any of these errors. I tried using 4.14 version as well but it did the same thing. It doesn't work for any of the versions.

Is it possible for me to find the download of the last version of UModel? Because that was the one that was working for me.

**Comment by gildor2** [comment]
Latest update just brings an update to UE4.18's USkeleton class serialization (just where UModel crashes now). If you used 4.18 before the update, then this means that PUBG uses pre-release version of UE4.18, and with newer update to the game they may switch to full 4.18 or pre-release 4.19 etc.

Regarding older UModel versions, they're all here on github:
https://github.com/gildor2/UModel/commits/master/umodel.exe

I'm intentionally committing all executables there.

**Comment by ArchUser87** [comment]
PUBG is using UE 4.16, I can load the Dacia model myself just right now...
![dacia](https://user-images.githubusercontent.com/25260650/34775588-d63d19ae-f667-11e7-8335-13a89f10a783.PNG)

**Comment by gildor2** [comment]
Thank you ArchUser87. I didn't expect that people may open an issue at github without trying obvious things, like - trying different engine versions.

**Comment by gildor2** [comment]
Post-close message. It seems PUBG uses pre-release version of UE4.18 which were supported by UModel before the recent update. Now UModel supports release 4.18, so PUBG can't be opened. What you can do:
a) wait until PUBG will update the engine again
b) use older UModel
c) find an older version of the game, which uses "stable" engine version.

**Comment by ShadowRanger** [comment]
That will explain it, thanks for the information.
