### ISSUE TITLE
Fortnite Current Version error!

### ISSUE THREAD

**Issue by ALIEN31ITA** [gildor2/UModel#46]
i get the "wrong tag" error, everytime i try to open a .uasset or something of fortnite, unpacked 3 days ago, wich is the new version of course with a quickbms script,

i read your faq it's says this error comes with XBOX360 titles, but i'm using the PC version 
(i know it doesn't exist for 360) so.... any fix in future? please? i'm also in your forum, as you can see you moved my post

**Comment by gildor2** [comment]
How did you unpack encrypted pak files?

**Comment by ALIEN31ITA** [comment]
i used a quickbms script, "unreal tournament 4" can be found in quickbms site

**Comment by gildor2** [comment]
http://www.gildor.org/smf/index.php/topic,3317.msg26479.html#msg26479
