### ISSUE TITLE
Blade And Soul EU Sound Track

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#50]
i am trying to extract the UPK Include the game soundtrack but umodel simply like dont want to extract this is what the console say

> Memory: allocated 309663 bytes in 876 blocks
Memory: allocated 309663 bytes in 876 blocks
Loaded in 0 sec, 1 allocs, 0.00 MBytes serialized in 0 calls.

but i can extract the rest upk of the game
[00009261.zip](https://github.com/gildor2/UModel/files/1727885/00009261.zip)

**Comment by gildor2** [comment]
Sounds are supported only for those games which use standard sound format. Nothing custom here. Sound support is just a secondary function of umodel, sorry.

**Comment by gildor2** [comment]
Well, before closing the thread I've decided to test the file you provided. And exported everything with no problems. Didn't you forget to enable sound export?

![image](https://user-images.githubusercontent.com/7008904/36848924-bc8041c0-1d73-11e8-8141-05518cd3aeff.png)

**Comment by DemonRem** [comment]
yes Gildor i did it's ok, sorry for a late respond
