### ISSUE TITLE
Cannot open include file: 'GL/gl.h'

### ISSUE THREAD

**Issue by BlueRaja** [gildor2/UModel#53]
When I follow the directions [here](https://github.com/gildor2/UModel#windows) to build on Windows, I get the following error when building:

> C:\Projects\CSharp\UModel\Core\CoreGL.h(8) : fatal error C1083: Cannot open include file: 'GL/gl.h': No such file or directory

Do I need to install [one of the many OpenGL SDKs](https://www.opengl.org/sdk/libs/) or something?

**Comment by gildor2** [comment]
Which Visual Studio version are you using? Do you have Windows Platform SDK (Windows Kit) installed, and if yes - which version? What build tool says when you're building the code? (I'd like to see the full log).

**Comment by BlueRaja** [comment]
I have VS 2013, 2015, and 2017 installed; the script appears to be using 2015

I'm not sure which Platform SDKs I have (if any), but I just tried installing the "Windows SDK for Windows 7 and .NET Framework 4", to no avail.

I'm not sure what you mean by "which build tool", but here is the full console output: https://pastebin.com/eiAw1W0k

**Comment by gildor2** [comment]
According to log, it uses VS 2013. And script didn't find a platform SDK installed.
NET framework is not needed, this is a native application.
Please check if you have a folder "C:\Program Files (x86)\Microsoft SDKs\Windows" and sub-folder v7.0A or v7.1. It should have Include/gl.

**Comment by BlueRaja** [comment]
I realize it's a native application, that was just the name of the Windows SDK installer from Microsoft.

I do have `C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A` but it does not have an `Include/GL` subfolder.  However the `v7.1A` subfolder does.  I was able to get it to build by renaming `v7.1A` to `v7.0A`.  Thanks!
