### ISSUE TITLE
Extracting SoundWave from non baked  asset

### ISSUE THREAD

**Issue by netdoggy** [gildor2/UModel#54]
Приветствую.
Пытался достать wav звуки из чистых SoundWave ассетов из ue 4.10, 4.18 и не вышло. 
Выдаёт невнятные ошибки из GUI, хотя через cli  если ткнуть прямо в asset, пишет, что не находит поля bLooped, SampleRate, etc.
Хочется перевести аудио в fmod, и при этом не и искать заного все сэмплы с разных мест.
Есть ли поддержка этого дела?

**Comment by gildor2** [comment]
Привет.
Только что проверил экспорт звука из UE4.19 (не-cooked ассет), всё работает. Если у вас появляются "невнятные ошибки", напишите их здесь.

**Comment by netdoggy** [comment]
Хорошо, 
через GUI указываю. папку с звуковыми ассетами, в GUI получаю список ассетов:
Если выбрать ассет и нажать export то:
```
Loading package: Spaceship/SS_Engine_Stutter_02.uasset Ver: 514/0 Engine: 0 Names: 19 Exports: 3 Imports: 5 Game: 1000000
Memory: allocated 264364 bytes in 1047 blocks
Loaded in 0 sec, 1 allocs, 0.00 MBytes serialized in 0 calls.
Exporting objects ...
Memory: allocated 264348 bytes in 1047 blocks
```
Не понятно заэкспортило объект или нет. Во всяком случае я нигде не нашел.

Если дабл клик то:
```
Loading package: StonesImpact/Mono/StonesImpact_Mono_6.uasset Ver: 514/0 Engine: 0 Names: 19 Exports: 3 Imports: 5 Game: 1000000
Memory: allocated 261627 bytes in 1020 blocks
Loaded in 0 sec, 1 allocs, 0.00 MBytes serialized in 0 calls.

The specified package(s) has no supported objects.

Class statistics:
    1 AssetImportData
    1 MetaData
    1 SoundWave
```

**Comment by netdoggy** [comment]
с 5й попытки вышло
umodel  -sounds -path=c:\Temp\qwe  audio_bioscanner -export -out=c:\Temp\qwe 
:)

**Comment by gildor2** [comment]
Параметр -sounds обязателен, а то звуки загружать не будет. А экспорт можно и из GUI сделать. Звуки включить тоже можно из GUI.

**Comment by netdoggy** [comment]
Да спасибо, понятно что работает, просто не был уверен, что оно вообще работоспособно на чистых юассетах, поэтому глубоко и не рыл.
