### ISSUE TITLE
Killing Floor 2. Can't export or view some packages

### ISSUE THREAD

**Issue by xDShot** [gildor2/UModel#55]
Some packages can't be exported and umodel shows error. For exampe, one of bugged package is _KFGame/BrewedPC/Packages/Weapons/P90/WEP_3P_P90_MESH.upk_

Error on export:
![2018-03-02 08-41-44](https://user-images.githubusercontent.com/4261659/36885088-d33bfddc-1df5-11e8-83f4-6d10c1738d19.png)

**Comment by gildor2** [comment]
Static meshes from this game are not supported
http://www.gildor.org/smf/index.php/topic,2694.0.html

Just disable them and go. I have no idea if anything else works, this game is even not in compatibility table.

**Comment by xDShot** [comment]
That worked, thanks for suggestion. I guess I'll put mag from 1st person model.

Skeletal meshes work fine though.
