### ISSUE TITLE
PUBG models (The specified package(s) has no supported objects.)

### ISSUE THREAD

**Issue by ReddeR1337** [gildor2/UModel#56]
I try to open vehicles and get this error (The specified package(s) has no supported objects.)
ver 4.16
Pak key `45DD15D6DD2DA50AEB71CE7A5284CF8EA498B2EC3D52B7E336F3EA0071CE44B3`
_______________
Пытаюсь открывать модели машин но они попросту не работают, все остальное как то местами, что то работает а что то нет
Может меня кто то пальцем ткнуть, может я что то не так делаю ?

**Comment by gildor2** [comment]
Ну, во-первых есть FAQ, там написано что такое "no supported objects". Во-вторых, форум где работает поиск. Ну а в-третьих, я записал несколько видео где показано как вообще искать в каких ассетах есть что-то, а в каких-нет. Tools - Scan content. Все ссылки есть в readme.txt и в меню umodel "Help".

**Comment by ReddeR1337** [comment]
@gildor2 на сайте у вас написано что support ver pubg test UE4.14 (2017) Но как я знаю они обновили на UE4.16 и игра уже не тест)))
Сейчас попробую все по мануалу и отпишусь

**Comment by lu03797** [comment]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:57)
Caused by: java.util.NoSuchElementException: Collection contains no element matc
hing the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:200)
        ... 1 more

**Comment by gildor2** [comment]
Man, please post exception message for the application which you're using (not umodel).
