### ISSUE TITLE
Um?

### ISSUE THREAD

**Issue by AnthonyFuller** [gildor2/UModel#58]
appMalloc:size=-1803666692 (total=46 Mbytes) <- FArray::Empty:-1581961323 x 12 <- SerializePackageFileSummary4 <- FPackageFileSummary<<:Ver=0/0 <- UnPackage::UnPackage:/FortniteGame/Content/Weapons/FORT_Rifles/Mesh/SK_SCAR.uasset, ver=508/0, game=ue4.14 <- UnPackage::LoadPackage:/FortniteGame/Content/Weapons/FORT_Rifles/Mesh/SK_SCAR.uasset <- CUmodelApp::ShowPackageUI <- Main:umodel_build=695

**Comment by AnthonyFuller** [comment]
I got that while trying to view a mesh.

**Comment by gildor2** [comment]
I see "Fortnite" word somewhere. Check the forum thread about this game. Posting issue here wasn't a cleaver step (a kind of "let's ask instead of search").

**Comment by AnthonyFuller** [comment]
Ok
