### ISSUE TITLE
Maybe I'm being stupid

### ISSUE THREAD

**Issue by AnthonyFuller** [gildor2/UModel#59]
Where are the previous versions? I can't find them.

**Comment by gildor2** [comment]
http://www.gildor.org/projects/umodel/faq
Look for "Where could I get older version of UModel?"

**Comment by AnthonyFuller** [comment]
Hold on. How do I download it?

**Comment by gildor2** [comment]
Well, it seems github changed the way how it works. However I didn't know that, so I had to do some checks (you had to do that by yourself!).

In history, select a version which you want to download. Press "<>" button. It will open repository for given commit. Now, select umodel.exe, and in new page - hit "Download" button.

**Comment by AnthonyFuller** [comment]
ok
![image](https://user-images.githubusercontent.com/24512050/37867913-20f405b2-2f97-11e8-93bb-94080dfd59a6.png)

**Comment by AnthonyFuller** [comment]
idk what version of UE fortnite is using

**Comment by AnthonyFuller** [comment]
![image](https://user-images.githubusercontent.com/24512050/37869397-919e9e3c-2fae-11e8-97c9-1ba89e6f18e3.png)
4.16 i know now

**Comment by AnthonyFuller** [comment]
the skeletal mesh is my problem

**Comment by AnthonyFuller** [comment]
CLOSED
