### ISSUE TITLE
Rocket League Nintendo Switch

### ISSUE THREAD

**Issue by KekMcGee** [gildor2/UModel#62]
Memory: bad allocation size 1091028673 bytes
appMalloc:size=1091028673 (total=0 Mbytes) <- FArray::Empty:1091028673 x 1 <- FString<< <- Name:0 <- UnPackage::LoadNameTable <- UnPackage::UnPackage:antenna_alien_sf.xxx, ver=868/20, game=ue3 <- UnPackage::LoadPackage:antenna_alien_sf.xxx <- CUmodelApp::ShowPackageUI <- Main:umodel_build=695

Samples: https://mega.nz/#!hhxWWDTC!ZQhyzR_IFZWx7Izq6KU5TW85jT2v4ngTgd2g8XedCMU

I would like to rip the exclusive cars(Mario/Luigi NSR, Samus Gunship), which aren't present in the PC Version.

**Comment by gildor2** [comment]
Man, what's "report issue"? It's about - something claimed to work, but it doesn't. Neither of "Rocket League" game, nor Nintendo Switch platform were reported as working. So, why are you reporting issue?

It seems I should disable "issue tracking" here. There were 1-2 CORRECT issues reported - from 62 (number of this "issue").
