### ISSUE TITLE
Some animations I can't export

### ISSUE THREAD

**Issue by AnthonyFuller** [gildor2/UModel#64]
Is there a reason for this?

**Comment by gildor2** [comment]
Depends on what you're exporting. Check the forum please, you should be able to find an answer.

**Comment by AnthonyFuller** [comment]
******** Loading object Skeleton'Fortnite_M_Avg_Player_Skeleton.Fortnite_M_Avg_Player_Skeleton' ********

/FortniteGame/Content/Animation/Game/MainPlayer/Emotes/Emote_BlowKiss.Emote_BlowKiss: unknown translation compression method: 4 (ACF_Fixed32NoW) - dropping track

******** Loading object Skeleton'Fortnite_M_Avg_Player_Skeleton.Fortnite_M_Avg_Player_Skeleton' ********

/FortniteGame/Content/Animation/Game/MainPlayer/Emotes/Emote_Dab.Emote_Dab: unknown translation compression method: 4 (ACF_Fixed32NoW) - dropping track

**Comment by AnthonyFuller** [comment]
ill put it on the fortnite forum
