### ISSUE TITLE
Sword Art Online: Fatal Bullet - Mesh files give an error when being read.

### ISSUE THREAD

**Issue by Ziiella** [gildor2/UModel#67]
When trying to load mesh files from SAO: Fatal Bullet, I get given this error.

```Loading package: Mesh/SKL_AM_HAIR_000_000.uasset Ver: 516/0 Engine: 0 [Unversioned] Names: 21 Exports: 1 Imports: 3 Game: 1000130
Memory: allocated 150144 bytes in 223 blocks
Loaded in 0 sec, 4 allocs, 0.00 MBytes serialized in 0 calls.
Loading Skeleton SKL_AM_HAIR_000_000 from package Mesh/SKL_AM_HAIR_000_000.uasset
******** Loading object Skeleton'SKL_AM_HAIR_000_000.SKL_AM_HAIR_000_000' ********
*** ERROR: Skeleton::Serialize(SKL_AM_HAIR_000_000): 4 unread bytes
LoadObject:Skeleton'SKL_AM_HAIR_000_000.SKL_AM_HAIR_000_000', pos=696, ver=516/0 (unversioned), game=ue4.19 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- UIMenuItem::HandleCommand <- UIMenuItem::HandleCommand <- CUmodelApp::WndProc <- VisualizerLoop <- Main:umodel_build=710
```

If needed, here is a zip with the file in question: https://cdn.discordapp.com/attachments/429759548937732097/433494652310781952/AM_HAIR_000_000.zip

Textures on the other hand though seem to work fine.

**Comment by gildor2** [comment]
Here was said that the game uses 4.17
http://www.gildor.org/smf/index.php/topic,6070.0.html

I see you're using 4.19.

**Comment by Ziiella** [comment]
Oh my bad, I was told it was 4.19. Sorry about that.

Setting it to 4.17 seems to work with most models, though some models have errors like with this one. 

```
*** ERROR: Package "Texture/T_AM_BODY_001_200_N.uasset": wrong name index -15588229
UnPackage::SerializeFName:pos=00000410 <- FPropertyTag<< <- CTypeInfo::SerializeProps <- UObject::Serialize <- UTexture3::Serialize4 <- UTexture2D::Serialize4 <- UTexture2D::Serialize <- LoadObject:Texture2D'T_AM_BODY_001_200_N.T_AM_BODY_001_200_N', pos=410, ver=513/0 (unversioned), game=ue4.17 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- CUmodelApp::ProcessKey:key=6F, down=1 <- VisualizerLoop <- Main:umodel_build=710
```

**Comment by gildor2** [comment]
You didn't tell me that you used 4.19 - error message told me :)

Give me a sample, please. It appears to be the same error as here:
http://www.gildor.org/smf/index.php/topic,2864.msg27433.html#msg27433
(but with a different game).

**Comment by Ziiella** [comment]
Sure, here you go. 
https://drive.google.com/open?id=1IS0TQCHoAGEN-0wfVrQ4v9_7LZqk0xvC
Had to upload it to google drive.

**Comment by Christmastree56** [comment]
Hey guys i'm relatively new to extracting assets from a game. I really want to use the 3D model characters from sword art online fatal bullet but i'm having some trouble finding the character assets to export. When I export whatever content I do find, i can see the meshes and assets i'm looking for in the loading bar but not in the folders. I believe umodel crashes too afterwards. If anyone knows what I can do to see theses meshes that would be awesome! These files are just some images of what I see. 
![barley any content](https://user-images.githubusercontent.com/36945912/42671519-5fd4b48c-862e-11e8-8b59-c7179aba7fea.PNG)
![no meshes 1](https://user-images.githubusercontent.com/36945912/42671523-66091c08-862e-11e8-8840-82956a3b7c35.PNG)
![no meshes 2](https://user-images.githubusercontent.com/36945912/42671530-6d1ced1c-862e-11e8-8eba-d8ac7a3f3fc6.PNG)
![confused](https://user-images.githubusercontent.com/36945912/42671533-70ad530e-862e-11e8-986f-d34a42a5e91b.PNG)

**Comment by Christmastree56** [comment]
Also I am using 4.17 as well

**Comment by gildor2** [comment]
"Trouble finding assets" is technically not an ISSUE, isn't it?
In UModel, there's menu with "Help" items, please watch tutorial videos.

**Comment by Christmastree56** [comment]
Yeah sorry. I Should have checked there first, I will take a look thanks!
