### ISSUE TITLE
UE4 Blueprint

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#68]
Dear @gildor2 

i want first know if in the feature of UModel it's be possible to extract the blueprint assest

in case if it's be possible would you add it?

**Comment by DemonRem** [comment]
i can save it but when i import it to UE4 it's isn't add it , i see the content with the notepad to see it and the file data very small much of the blueprint is like between 30MB it's only 7mb

**Comment by gildor2** [comment]
Yes, you can't load "extracted" uasset files into editor because it ignores cooked packages. However I think I answered to your question - "it is possible to extract blueprint".
