### ISSUE TITLE
build.sh: ./make.pl: /usr/bin/perl: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by xoyojank** [gildor2/UModel#69]
bash build.sh
build.sh: ./make.pl: /usr/bin/perl: bad interpreter: No such file or directory
build.sh: ./Tools/genmake: /usr/bin/perl: bad interpreter: No such file or directory
build.sh: /usr/BuildTools/vc32tools: /bin/bash: bad interpreter: No such file or directory

**Comment by gildor2** [comment]
You didn't provide much information, so I can only assume. You're trying to build for Windows. And you didn't follow my instructions for building the tool. Bash can't even find itself.

Probably PATH variable is not correct.

**Comment by xoyojank** [comment]
I followed your instructions, copied build tools and set path variable…finnally I generated makefile in mingw32, build in VS cmd window successfully

**Comment by xoyojank** [comment]
win32 could not link successfully with the latest build tools, so I changed to build  win64. Compiler: VS2015, OS: Win10 64bit

**Comment by xoyojank** [comment]
i fixed error by creating 2 makefiles for win32 & win64 build: https://github.com/xoyojank/UModel
