### ISSUE TITLE
RIME: UAnimSequence4::Serialize error 

### ISSUE THREAD

**Issue by xoyojank** [gildor2/UModel#71]
![image](https://user-images.githubusercontent.com/2873643/39390311-4b288206-4ac5-11e8-9746-fb60e198f1a9.png)
![image](https://user-images.githubusercontent.com/2873643/39390313-4f8b68f4-4ac5-11e8-8a4e-b03faaaaf70d.png)
it seems the array size (65536) is large than the file size (93127 - 48642)
![image](https://user-images.githubusercontent.com/2873643/39390321-6a7ec962-4ac5-11e8-92fe-4450f9de2412.png)

**Comment by gildor2** [comment]
http://www.gildor.org/smf/index.php/topic,6027.0.html

**Comment by xoyojank** [comment]
is there any way to solve the problem? (do not serialize unknown fields?)

**Comment by gildor2** [comment]
No way without research and coding.

**Comment by gildor2** [comment]
I've fixed loading of some animation tracks made with UE4 before 4.13. This change affects Rime, this game should be fully supported now (tested all animation tracks, all works).
