### ISSUE TITLE
ERROR: Memory: bad allocation size 943194112 bytes

### ISSUE THREAD

**Issue by oscarman** [gildor2/UModel#72]
plis help, this error is displayed on the screen when i try to open a model with skeleton:

ERROR: Memory: bad allocation size 943194112 bytes
appMalloc:size=943194112 (total=65 Mbytes) <- FArray::Empty:16842752 x 56 <- TArray::Serialize:0/0 <- FStaticLODModel4<< <- TArray::Serialize:0/1 <- USkeletalMesh4::Serialize <- LoadObject:SkeletalMesh4'Pickaxe_BatSickle.Pickaxe_BatSickle', pos=1708, ver=513/0 (unversioned), game=ue4.16 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- UIMenuItem::HandleCommand <- UIMenuItem::HandleCommand <- CUmodelApp::WndProc <- VisualizerLoop <- Main:umodel_build=761

this error is displayed at moment of extrat or open any object (model with skeleton(mesh))of Fortnite:

![image](https://user-images.githubusercontent.com/19935179/40893050-bf17ea74-6764-11e8-9392-9efcc13cfee0.png)

can u help me?.

**Comment by gildor2** [comment]
I see mistakes in your usage. However, providing you a direct answer won't help you, you'll return here with any other noob error. For the beginning, I'd recommend you to learn how to use google. Most likely you'll find this thread after that:

http://www.gildor.org/smf/index.php/topic,3317.0.html

And I hope you will notice the very first in that thread, it is marked with large bold colored text, saying that it MUST be read.

**Comment by oscarman** [comment]
thanks, sorry for the loss of time.
