### ISSUE TITLE
Pak file has unsupported version 6

### ISSUE THREAD

**Issue by Kshopper93** [gildor2/UModel#76]
Get this error on Fortnite:

Pak file has unsupported version 6
FPakVFS::ReadDirectory <- MountVFS <- appRegisterGameFile:E:\Fortnite\Epic Games\Fortnite\FortniteGame/Content/Paks/pakchunk0-WindowsClient.pak <- ScanGameDirectory <- ScanGameDirectory <- ScanGameDirectory <- appSetRootDirectory:dir=E:\Fortnite\Epic Games\Fortnite\FortniteGame <- Main:umodel_build=790

Can someone help me?

**Comment by AeonLucid** [comment]
See http://www.gildor.org/smf/index.php/topic,6134.msg28752.html#msg28752.
