### ISSUE TITLE
Mesh Coords Error

### ISSUE THREAD

**Issue by DemonRem** [gildor2/UModel#77]
when i import SAO Fatal Bullet Mesh

Body , Face , Hair

body coords is correct the importation goes well

but when import hair & face they going on in the bottom where foot coords i think the ActorXImport is wrong, or something that i doing is wrong

**Comment by gildor2** [comment]
It would be better if you'd provide screenshots. Your explanation is absolutely unclear.

**Comment by DemonRem** [comment]
ok give me few mintues

**Comment by DemonRem** [comment]
![umodel](https://user-images.githubusercontent.com/29927382/42174049-b8085d32-7e29-11e8-8302-6119b79de86f.png)

look

**Comment by gildor2** [comment]
Check importer's log (F11, "listener window"). May be there are some errors there.
Also check if you're using latest importer.
AND try merging meshes in UModel itself, check how this will work. Is head a SkeletalMesh or StaticMesh? Does it use the same skeleton as body mesh?

**Comment by DemonRem** [comment]
i am using the ms script from the git

**Comment by DemonRem** [comment]
@gildor2 

there is no any error look

`Welcome to MAXScript.


Read mesh: 6068 verts, 6346 wedges, 8698 tris, 1 materials, 16 bones, 10208 influences
Unable to find texture M_HAIR_022_000
Loaded in 0.756 sec
Read mesh: 2980 verts, 3417 wedges, 5564 tris, 4 materials, 49 bones, 6580 influences
Unable to find texture M_AF_FACE_022_000
Unable to find texture M_AF_EYEL_022_000
Unable to find texture M_AF_EYER_022_000
Unable to find texture M_AF_EYEBROWS_022_000
Loaded in 0.658 sec
Read mesh: 22469 verts, 24640 wedges, 27253 tris, 4 materials, 80 bones, 48436 influences
Loading UV set #2 ...
Unable to find texture M_AF_SKIN_000_000
Unable to find texture M_AF_BODY_022_000
Unable to find texture M_AF_BODY_022_000
Unable to find texture M_AF_BODY_022_000
Loaded in 3.275 sec
`

**Comment by DemonRem** [comment]
from some reason it's happened with UE4 games only i never had this error on any UE3 games

**Comment by DemonRem** [comment]
![umodel](https://user-images.githubusercontent.com/29927382/42181175-a336cbe6-7e42-11e8-8d9b-60e9239e1451.png)

this is the body

![umodel2](https://user-images.githubusercontent.com/29927382/42181234-ddaf3bf0-7e42-11e8-9aed-5360fba5e130.png)

this is the face

![umodel2](https://user-images.githubusercontent.com/29927382/42181250-ebfa46b4-7e42-11e8-94bf-7225bb4c0268.png)

this is the hair

![umodel3](https://user-images.githubusercontent.com/29927382/42181258-f153b7c6-7e42-11e8-9553-2895a019f178.png)

**Comment by gildor2** [comment]
Did you try importing body, then face, then hair (in this order)?

**Comment by DemonRem** [comment]
yes

**Comment by DemonRem** [comment]
as i notice UE4 using different way then UE3 maybe the script is outdated and Not Support fully for UE4

**Comment by gildor2** [comment]
This is not "UE4". This is a particular game. I suppose that if you'll try to show body with head in umodel, it won't attach them also. If umodel will show meshes attached, then this can be fixed in ActorX. If not - I doubt anything could be done here.

The problem here, probably, is different skeletons used for head and body.

**Comment by DemonRem** [comment]
so what you suggest me to do?

**Comment by gildor2** [comment]
I can't suggest anything really useful - I don't have assets to check by myself. 
May be you should attach head to some body's bone.

**Comment by DemonRem** [comment]
ok thank you @gildor2
