### ISSUE TITLE
RocketLeague updated a week ago, I can't decrypt the files at this moment

### ISSUE THREAD

**Issue by remizik** [gildor2/UModel#78]
Hi,

never tried before today so I can't confirm it was working before the RL update (june 27).
This is the error I get : 

![image](https://user-images.githubusercontent.com/24875086/42224487-76b71092-7eda-11e8-91d3-5c4994eefe94.png)

Thanks :)

**Comment by AltimorTASDK** [comment]
When appDecryptAES is called with the default KeyLen parameter of -1, it attempts to use strlen to determine the key size. This fails with Rocket League's AES key because it contains a null byte.

**Comment by remizik** [comment]
I understood some of these words.
haha :D 
I'm a total noob, does it mean I can fix it myself by changing something on my machine ? or does the app itself need  an update ?
Thanks :)

**Comment by AltimorTASDK** [comment]
Umodel needs an update to fix it, but it's a simple bug and doesn't require any changes to Rocket League package handling.

**Comment by remizik** [comment]
Ok then, good news :)
I'll keep an eye on the website then, hopefully it will get updated soon :)
Thanks a lot

**Comment by remizik** [comment]
there you go :)
https://we.tl/5BPkpx01gU

**Comment by gildor2** [comment]
Done. Please download new umodel.

**Comment by remizik** [comment]
Looks like it works great ! thanks a lot ! :)
