### ISSUE TITLE
Memory: bad allocation size

### ISSUE THREAD

**Issue by UntouchedOdin0** [gildor2/UModel#80]
I don't know why, but whenever I try and load up a character in Umodel, I get the error saying bad allocation size 943194112 bytes.

Here is the full error log 

> appMalloc:size=943194112 (total=46 Mbytes) <- FArray::Empty:16842752 x 56 <- TArray::Serialize:0/0 <- FStaticLODModel4<< <- TArray::Serialize:0/1 <- USkeletalMesh4::Serialize <- LoadObject:SkeletalMesh4'F_MED_Valor_01_Export.F_MED_Valor_01_Export', pos=1597E, ver=513/0 (unversioned), game=ue4.17 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_build=777

**Comment by gildor2** [comment]
There could be different reasons for that. Unsupported game, incorrectly set up UE4 engine version, etc. This is absolutely "noob" situation, and github is not a place for asking such questions, sorry. Github issue tracker is a "technical" place.

**Comment by gildor2** [comment]
Closing as there's no response (why opening issue then?)
