### ISSUE TITLE
Fortnite 5.0.0 changes

### ISSUE THREAD

**Issue by AeonLucid** [gildor2/UModel#81]
**To all the fortnite players looking at this, DONT CONTACT ME.**

I'm currently updating my own program and noticed that UModel had the same issues.
http://www.gildor.org/smf/index.php/topic,3317.msg29491.html#msg29491

Read that you had no time to update this, so I thought, lets contribute a bit.
I'll note the changes found so you can apply them easily as well.

**TextureDerivedData.cpp**
- UTexture::SerializeCookedPlatformData()
  - `skipOffset` changed from `int32` to `int64`.

**Texture2D.cpp**
- FTexture2DMipMap::Serialize
  - `SizeZ` (int32) added after `SizeY` (depth)

**Comment by GambitAnimating** [comment]
Aye thanks! ^^

**Comment by Greenylie** [comment]
Hi, sorry I'm not an expert, i just wanted to ask how to apply these changes...
What should i do?

**Comment by GambitAnimating** [comment]
@Greenylie http://www.mediafire.com/file/nt6wwsf5rf0blaa/UModel.7z Github isn't really the place to ask though.

**Comment by Greenylie** [comment]
I know, but i didn't know where to ask, i'm new in this sort of things, Thanks for your help

**Comment by gildor2** [comment]
If you're at github, then you're a programmer. If you're a programmer, then such things shouldn't be hard for you.

**Comment by gildor2** [comment]
I've added support for updated UE4. In addition to Texture2D changes, there also changed normal vector format. These are UE4.20 features.
