### ISSUE TITLE
Umodel error

### ISSUE THREAD

**Issue by Tezeract** [gildor2/UModel#83]
When trying to load something in umodel build 801 it gives me an error; Example:
FString<< <- FTexturePlatformData<< <- UTexture2D::Serialize4 <- UTexture2D::Serialize <- LoadObject:Texture2D'T_St_Patrick_Hat_D.T_St_Patrick_Hat_D', pos=445, ver=516/0 (unversioned), game=ue4.19 <- UObject::EndLoad <- CUmodelApp::ShowPackageUI <- Main:umodel_build=801
 Pls help. <3 Edit: Nevermind I reinstalled it and it worked.

**Comment by gildor2** [comment]
http://www.gildor.org/smf/index.php/topic,3317.675.html
