### ISSUE TITLE
unknown compression flags: 514

### ISSUE THREAD

**Issue by ohgeek** [gildor2/UModel#84]
I'm trying to open the resources of Paladins(Tencent version) and I have checked the "List of supported games".It says it's fully support Paladins, but I get an error saying unknown compression flags: 514 when I open some upk files.
It seems Paladins has been updated and your tool can't recognize it correctly.
Here is the call stack:
`appDecompress:CompSize=42835 UncompSize=131072 Flags=0x202 <- DecompressBlock:block=F69+A753 <- FUE3ArchiveReader::PrepareBuffer <- FUE3ArchiveReader::Serialize <- FArchive::ByteOrderSerialize <- FString<< <- Name:0 <- UnPackage::LoadNameTable <- UnPackage::UnPackage:ChaosGame/CookedPCConsole/Startup.upk, ver=893/0, game=ue3 <- UnPackage::LoadPackage:startup_xxx <- UnPackage::CreateImport:ChaosGame/CookedPCConsole/FT_Tutorial.upk:80 <- UnPackage::SerializeUObject <- ReadProperty:(UMaterialInstanceConstant.Parent, TagPos=1AB8F) <- CTypeInfo::SerializeUnrealProps <- UObject::Serialize <- LoadObject:MaterialInstanceConstant'FT_Tutorial.MIC_FC_Materials_WoodTrim', pos=1ABAB, ver=893/0, game=ue3 <- UObject::EndLoad <- LoadWholePackage:FT_Tutorial <- CUmodelApp::ShowPackageUI <- Main:umodel_build=850`
And the website of Paladins(Tencent version) is http://qhyx.qq.com/. Hoping you can fix it soon.  :)

**Comment by gildor2** [comment]
I think forum thread about this game has solution.

**Comment by ohgeek** [comment]
Sorry I forget to check your forum.Have a good day!
