### ISSUE TITLE
A Hat in Time: ERROR: RawArray item size mismatch: expected 12, serialized 20

### ISSUE THREAD

**Issue by Mygod** [gildor2/UModel#86]
```
> .\umodel.exe -export -sounds 'A Hat in Time\HatinTimeGame\CookedPC\Maps\hub\hub_spaceship.umap'
Detected game root A Hat in Time/HatinTimeGame/CookedPC
Found 79 game files (0 skipped) at path "A Hat in Time/HatinTimeGame/CookedPC"
Loading package: Maps/hub/hub_spaceship.umap Ver: 881/5 Engine: 12097 Names: 9143 Exports: 32803 Imports: 2046 Game: 800000
Loaded in 0.037 sec, 3399 allocs, 0.00 MBytes serialized in 0 calls.
Loading AnimSet Conductor_Anims from package Maps/hub/hub_spaceship.umap
WARNING: ArrayProperty "UAnimSet::PreviewSkelMeshNames" was not found
Loading AnimSequence AnimSequence_11 from package Maps/hub/hub_spaceship.umap
WARNING: BoolProperty "UAnimSequence::bWasCompressedWithoutTranslations" was not found
WARNING: ByteProperty "UAnimSequence::ScaleCompressionFormat" was not found
WARNING: ArrayProperty "UAnimSequence::CompressedScaleOffsets" was not found
******** Loading object AnimSequence'hub_spaceship.AnimSequence_11' ********
*** ERROR: RawArray item size mismatch: expected 12, serialized 20

SerializeBulkArray <- FRawAnimSequenceTrack<< <- TArray::Serialize:1/68 <- UAnimSequence::Serialize <- LoadObject:AnimSequence'hub_spaceship.AnimSequence_11', pos=4354B6, ver=881/5, game=ue3 <- UObject::EndLoad <- Main:umodel_build=859
```

Here's [the version that works with UModel](http://itorrents.org/torrent/C9183CB856BD375D799A0963D4A422D9372A97C5.torrent) and here's [the version that doesn't](http://itorrents.org/torrent/FE3470F5DD2089962DEB6B860131AB28CDAA6621.torrent). (sorry I don't know where to get old versions besides pirating the game)

**Comment by gildor2** [comment]
This game has some problems, it has been reported here:
http://www.gildor.org/smf/index.php/topic,6228.0.html

And sorry, I'm not going to spend any time on that.

**Comment by Mygod** [comment]
Does this mean the game developer has full control over the file format and not the engine?

**Comment by gildor2** [comment]
Every UE developer has full control over the any piece of code.

**Comment by LikeLakers2** [comment]
@gildor2 My apologies for bumping this thread, but I contacted the Hat in Time devs on this, and they replied with this:

>might be because we've changed the model format for performance reasons
>we dont really have any way of making umodel support Hat in Time since we dont work on umodel
>they could reach out to the umodel developer

Unlike what you said in the thread, I don't think there's any reason for them to want to bar people from exporting models, since back when the modding tools were first released, they seemed in favor of people being able to export content from the packages -- and this response seems to imply the same.

That said, does this change your stance on the matter? Or do you still not want to spend any time on this?
