### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gildor2/UModel#88]
I would like to point out that identifiers like “[`__CORE_GL_H__`](https://github.com/gildor2/UModel/blob/eb12e285dca665791741583eb34b53e3a792b845/Core/CoreGL.h#L1 "Update candidate")” and “[`__GAME_LIST_H__`](https://github.com/gildor2/UModel/blob/94aed39291c201692ddd7a7306a69d0cf976f718/Unreal/GameDatabase.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gildor2** [comment]
Sorry, I do not bother for coding standard of some unknown organization. Language rules has nothing about how should I name defines etc. There's no conflict with other names, so no error at all.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by gildor2** [comment]
There's no undefined behavior caused by these defines.

**Comment by elfring** [comment]
The C++ standard language specification expresses such an aspect [when you tamper with the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers").

**Comment by gildor2** [comment]
Well, I'll take it under my own responsibility. Thanks. I do not use many things which "C++ coding standard" assumes. For example, STL.

**Comment by gildor2** [comment]
Just for reference of conversation:
https://github.com/curl/curl/issues/2838
