### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [gildor2/UModel#89]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [FPakVFS](https://github.com/gildor2/UModel/blob/a46f5ff83966792cea61c0ec497d4c41fa00e323/Unreal/UnArchivePak.h#L349 "Destructor for FPakVFS")
* [FUE3ArchiveReader](https://github.com/gildor2/UModel/blob/82a1075b8399cc5a52863ca79ddf6fc0b3333d3d/Unreal/UnPackageUE3Reader.h#L56 "Destructor for FUE3ArchiveReader")
* [CVertMeshInstance::FreeRenderBuffers](https://github.com/gildor2/UModel/blob/fc8306e43d31dfb646c6888dbb55a6437f0e3a60/MeshInstance/VertMeshInstance.cpp#L31 "CVertMeshInstance::FreeRenderBuffers function")

**Comment by gildor2** [comment]
Yes, I know. I prefer to check pointer for NULL before deleting. This is my coding style.

**Comment by gildor2** [comment]
I've checked your github page. I see all of your activity could be called as "issue generator" - 98 issues in August, 57 issues in July. I'm afraid to look farther. Please leave all "language problems" in my repositories to myself, I'll fix anything really important what I or others will find.

Regards,
Konstantin

**Comment by elfring** [comment]
Can your software become a bit more efficient also at the mentioned source code places?

**Comment by gildor2** [comment]
Efficiency in destructor? This
1. won't make it faster - I know what is "optimization" and "time critical code", these places are not those ones
2. make code 20 bytes smaller - with file alignment of 512 bytes, this won't help.

**Comment by gildor2** [comment]
Just for reference of conversation:
https://github.com/curl/curl/issues/2838

**Comment by elfring** [comment]
Would you like to take another look at integrated patches for discussed software change possibilities?

**Comment by gildor2** [comment]
Go away from github, kid. This is a place where developers work.
