### ISSUE TITLE
How does *.props.txt work? 

### ISSUE THREAD

**Issue by rancent2017** [gildor2/UModel#90]
Is it a "Blender" file? I can't find a description from the website . How does it import ？

**Comment by gildor2** [comment]
It is a "human" TEXT file. You should read it, and depending on your personal experience - use that information.

**Comment by rancent2017** [comment]
Ok, then where should I enter them? Blender or UE4Editor ?

**Comment by gildor2** [comment]
Did you really read and understood my answer?

**Comment by rancent2017** [comment]
Yes , I think about blueprint system ，i use translation and may be it incorrect . In short, thanks

**Comment by gildor2** [comment]
Your question was about material, and now you're talking about Blueprint. And about Blender at the same time. Sorry, but I did not understand what you want at all.

**Comment by rancent2017** [comment]
ok.... thank you.

**Comment by gildor2** [comment]
I used the format which I used for umodel.cfg, it was developed many years ago (for SkelEdit application). It is intended for human readability and easy editing, and it has syntax which is very close to json. It just doesn't have quotes and commas everywhere as json have.
