### ISSUE TITLE
Switch Swizzling support?

### ISSUE THREAD

**Issue by Supurreme** [gildor2/UModel#97]
I'm attempting to extract some models from a switch game and while i can get the meshes out just fine with umodel, all the textures come out scrambled due to the switch's handling of textures. Would it be possible to add support for dealing with this in the future?

here's a thread researching the issue: https://www.vg-resource.com/thread-31389-page-2.html

**Comment by gildor2** [comment]
It is planned, may be for next year.

**Comment by gildor2** [comment]
Done some time ago.
