### ISSUE TITLE
Just moved from actorx because it was an issue here not there

### ISSUE THREAD

**Issue by ThymeParadox** [gildor2/UModel#98]
Uppon opening Unsupported Version 7 appears next to all lines of code in the command line, and no files can be viewed in 3d or exported but I can see all paths and file names

**Comment by gildor2** [comment]
Opening WHAT? Where appears? Is something crashed?

**Comment by gildor2** [comment]
I see you didn't read the log. "version 7" is informational warning message, means almost nothing for Fortnite. The main message here is "The specified package(s) has no supported objects.". Try to understand what it says. If it's too hard, please refer to FAQ.

**Comment by gildor2** [comment]
And please use forum next time for questions. Issue tracker is supposed to be used for bug reports etc, but not for usage questions.

**Comment by ThymeParadox** [comment]
ok thank you
